# 第十一章 异常 Exception

# 11.1 Syntax Errors

```
SyntaxError: invalid syntax
```

# 11.2 Exceptions
```
10 * (1/0)
ZeroDivisionError: division by zero
```
```
4 + spam*3
NameError: name 'spam' is not defined
```
```
'2' + 2
TypeError: Can't convert 'int' object to str implicitly
```

# 11.3 Handling Exceptions
```
while True:
    try:
        x = int(input("Please enter a number: "))
        break
    except ValueError:
        print("Oops! That was no valid number. Try again...")
    except (RuntimeError, TypeError, NameError):
        pass
```
# 11.4 异常种类
```
ZeroDivisionError
NameError
TypeError
ValueError
Exception:捕获所有异常
```
# 11.5 得到异常的具体信息
```
try:
    pass
except NameError as ne:
    print(ne.message)
```
# 11.6 finally
不管有没有遇到异常，都会执行```finally```的内容，且在抛出异常之前执行。一般可以执行关闭文件等操作。
```
try:
    pass
except ValueError:
    pass
finally:
    print('we should close the file here.')
```
# 11.7 warning
## 11.7.1 发出warning
需要让用户知道的问题，但又不想停止程序，这时候我们可以使用警告.
```
import warnings
def month_warning(m):
    if not 1<= m <= 12:
        msg = "month (%d) is not between 1 and 12" % m
        warnings.warn(msg, RuntimeWarning)

month_warning(13)

#output
D:\Program Files (x86)\PyCharm Community Edition 2017.1.1\helpers\pydev\pydevconsole.py:4: RuntimeWarning: month (13) is not between 1 and 12
```
## 11.7.2 忽略warning
```
warnings.filterwarnings(action = 'ignore', category = RuntimeWarning)

month_warning(13)
```